version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:14.10.2-ce.0'
    restart: always
    hostname: 'gitlab.example.com'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['time_zone'] = 'UTC'
      TZ: America/Sao_Paulo
    ports:
      - '8080:80'
      - '8443:443'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

